'use client';
import { RequestGate } from '../lib/request-gate.mjs';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, ChevronRight, Film, Grid2X2, Layers, Play, Pause, ScanLine, Sparkles } from 'lucide-react';
type Summary={frameCount:number;frameWidth:number;frameHeight:number;atlasWidth:number;atlasHeight:number;fps:number};
type Result={summary:Summary;atlasBase64:string;sequenceZipBase64:string;atlasJSON:string;inspection:Record<string,unknown>;metadata:{frames:Array<{frame:{x:number;y:number;w:number;h:number}}>}};
const readFile=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});
function save(data:string,name:string,mime:string,base64=true){let bytes:Uint8Array<ArrayBuffer>;if(base64){const raw=atob(data);bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);}else bytes=new TextEncoder().encode(data);const url=URL.createObjectURL(new Blob([bytes],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function NumberField({label,value,onChange,min=0,max=2048}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){return <label className="number-field"><span>{label}</span><input type="number" value={value} min={min} max={max} onChange={e=>onChange(Number(e.target.value))}/></label>;}
export default function Studio({signedIn,signInPath}:{signedIn:boolean;signInPath:string}){
 const [file,setFile]=useState<File|null>(null),[base64,setBase64]=useState(''),[mode,setMode]=useState<'single'|'grid'|'motion'>('single'),[columns,setColumns]=useState(4),[rows,setRows]=useState(2),[count,setCount]=useState(8),[fps,setFps]=useState(12),[padding,setPadding]=useState(8),[threshold,setThreshold]=useState(0),[align,setAlign]=useState('center'),[dx,setDx]=useState(2),[dy,setDy]=useState(0),[motionFrames,setMotionFrames]=useState(12),[trim,setTrim]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null),[view,setView]=useState<'motion'|'atlas'>('motion'),[playing,setPlaying]=useState(true),[frame,setFrame]=useState(0),[dragging,setDragging]=useState(false);
 const requestGate=useRef(new RequestGate()); const input=useRef<HTMLInputElement>(null); const canvas=useRef<HTMLCanvasElement>(null); const image=useRef<HTMLImageElement|null>(null);
 useEffect(()=>{if(!result)return;const img=new Image();img.onload=()=>{image.current=img;setFrame(0);draw(img,0);};img.src='data:image/png;base64,'+result.atlasBase64;return()=>{img.onload=null;if(image.current===img)image.current=null;};},[result,view]);
 function draw(img:HTMLImageElement,index:number){const c=canvas.current;if(!c||!result)return;const ctx=c.getContext('2d');if(!ctx)return;const s=result.summary;c.width=view==='atlas'?s.atlasWidth:s.frameWidth;c.height=view==='atlas'?s.atlasHeight:s.frameHeight;ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;if(view==='atlas')ctx.drawImage(img,0,0);else {const f=result.metadata.frames[index]?.frame;const cols=Math.floor(s.atlasWidth/s.frameWidth);ctx.drawImage(img,f?.x??(index%cols)*s.frameWidth,f?.y??Math.floor(index/cols)*s.frameHeight,s.frameWidth,s.frameHeight,0,0,s.frameWidth,s.frameHeight);}}
 useEffect(()=>{if(image.current)draw(image.current,frame);},[frame,view,result]);
 useEffect(()=>{if(!playing||!result||view==='atlas')return;const timer=setInterval(()=>setFrame(f=>(f+1)%result.summary.frameCount),1000/result.summary.fps);return()=>clearInterval(timer);},[playing,result,view]);
 async function choose(next:File|undefined){if(!next)return;setError('');if(next.type!=='image/png'&&!next.name.toLowerCase().endsWith('.png')){setError('PNG 파일을 선택해 주세요');return;}if(next.size>2_000_000){setError('2 MB 이하의 PNG를 선택해 주세요');return;}const token=requestGate.current.start();setBusy(true);setResult(null);try{const b64=await readFile(next);if(!requestGate.current.isCurrent(token))return;const response=await fetch('/api/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pngBase64:b64})});const inspected=await response.json() as {error?:string};if(!requestGate.current.isCurrent(token))return;if(!response.ok)throw new Error(inspected.error||'PNG를 확인하지 못했어요');setFile(next);setBase64(b64);}catch(e){if(requestGate.current.isCurrent(token))setError(e instanceof Error?e.message:'파일을 읽지 못했어요');}finally{if(requestGate.current.isCurrent(token))setBusy(false);}}
 async function build(){if(!base64)return;const token=requestGate.current.start();setBusy(true);setError('');try{const options={name:'sprite',fps,alphaThreshold:threshold,source:mode==='grid'?{kind:'grid',columns,rows,count}:{kind:'single'},normalize:{padding,align,trim},...(mode==='motion'?{motion:{frames:motionFrames,dx,dy}}:{})};const response=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pngBase64:base64,options})});const data=await response.json() as Result & {error?:string};if(!requestGate.current.isCurrent(token))return;if(!response.ok)throw new Error(data.error||'처리에 실패했어요');setResult(data);setFrame(0);setPlaying(true);}catch(e){if(requestGate.current.isCurrent(token))setError(e instanceof Error?e.message:'처리에 실패했어요');}finally{if(requestGate.current.isCurrent(token))setBusy(false);}}
 return <div className="studio-shell"><header className="topbar"><a className="wordmark" href="/" aria-label="Dot Motion Studio"><span className="mark"><Layers size={19}/></span><strong>dot<span>motion</span></strong></a><span className="private"><span/>PNG studio</span><a className="docs-link" href="/guide">사용 가이드 <ChevronRight size={14}/></a>{!signedIn&&<a className="signin-link" href={signInPath} target="_top">ChatGPT로 로그인</a>}</header>
 <main><div className="page-heading"><div><p className="eyebrow">A LITTLE MOVEMENT, ALL YOURS</p><h1>이미지에 움직임을 더하세요<span>.</span></h1><p>PNG에서 프레임을 정리하고, 나만의 스프라이트로 내보내세요</p></div><span className="version">STUDIO / 01</span></div>
 <div className="workspace"><aside className="controls"><section><div className="section-title"><span className="step">01</span><h2>원본 이미지</h2><span className="subtle">PNG · 최대 2 MB</span></div><input ref={input} type="file" accept="image/png" className="sr-only" onChange={e=>choose(e.target.files?.[0])}/><button className={'upload '+(dragging?'dragging':'')} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);choose(e.dataTransfer.files[0]);}}>{file?<><img src={'data:image/png;base64,'+base64} alt="선택한 원본 PNG"/><strong>{file.name}</strong><span>{(file.size/1024).toFixed(1)} KB · 눌러서 변경</span></>:<><span className="upload-icon"><ArrowUpFromLine size={22}/></span><strong>PNG를 여기에 놓으세요</strong><span>또는 눌러서 파일 선택</span></>}</button></section>
 <section><div className="section-title"><span className="step">02</span><h2>작업 방식</h2></div><div className="modes">{[{key:'single',label:'한 장 정리',icon:<ScanLine size={17}/>},{key:'grid',label:'시트 나누기',icon:<Grid2X2 size={17}/>},{key:'motion',label:'2D 이동',icon:<Film size={17}/>}].map(m=><button key={m.key} className={mode===m.key?'active':''} onClick={()=>{setMode(m.key as typeof mode);if(m.key==='grid')setTrim(false);}}>{m.icon}{m.label}</button>)}</div>{mode==='grid'&&<div className="fields"><NumberField label="가로 칸" value={columns} onChange={setColumns} min={1} max={64}/><NumberField label="세로 칸" value={rows} onChange={setRows} min={1} max={64}/><NumberField label="프레임 수" value={count} onChange={setCount} min={1} max={64}/></div>}{mode==='motion'&&<><div className="fields"><NumberField label="프레임 수" value={motionFrames} onChange={setMotionFrames} min={1} max={64}/><NumberField label="X / 프레임" value={dx} onChange={setDx} min={-256} max={256}/><NumberField label="Y / 프레임" value={dy} onChange={setDy} min={-256} max={256}/></div><p className="hint">한 장의 이미지를 일정한 픽셀 간격으로 이동해요</p></>}</section>
 <section><div className="section-title"><span className="step">03</span><h2>정리 & 타이밍</h2></div><div className="fields two"><NumberField label="재생 속도 · FPS" value={fps} onChange={setFps} min={1} max={60}/><NumberField label="여백 · px" value={padding} onChange={setPadding} max={256}/></div><div className="select-row"><label htmlFor="alignment">이미지 정렬</label><select id="alignment" value={align} onChange={e=>setAlign(e.target.value)}><option value="center">가운데</option><option value="bottom">바닥 맞춤</option></select></div><label className="check"><input type="checkbox" checked={trim} onChange={e=>setTrim(e.target.checked)}/>투명한 바깥 여백 자르기</label><label className="range-label" htmlFor="alpha">알파 정리 <span>{threshold} / 254</span></label><input className="range" id="alpha" type="range" min={0} max={254} value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><p className="hint">임계값 이하의 투명도만 제거해요. 배경 인식 기능은 없어요</p></section>
 {error&&<p role="alert" className="error">{error}</p>}<button className="build-button" onClick={build} disabled={!file||busy}>{busy?<span className="spinner"/>:<Sparkles size={18}/>} {busy?'프레임을 정리하고 있어요':'스프라이트 만들기'}{!busy&&<ChevronRight size={18}/>}</button><p className="privacy-note">{!signedIn&&<>이미지 처리는 ChatGPT 로그인 후 이용할 수 있어요<br/></>}이미지는 요청 중에만 처리하고 서버에 저장하지 않아요</p></aside>
 <div className="preview-column"><section className="preview-panel"><div className="preview-toolbar"><div className="tabs"><button className={view==='motion'?'active':''} onClick={()=>setView('motion')}><Play size={13}/>미리보기</button><button className={view==='atlas'?'active':''} onClick={()=>setView('atlas')}><Grid2X2 size={14}/>아틀라스</button></div><span className="alpha-badge">TRANSPARENT</span></div><div className={'stage '+(!result?'empty':'')}>{result?<canvas ref={canvas} aria-label="스프라이트 미리보기"/>:<div className="empty-state"><div className="empty-layers"><span/><span/><span><Layers size={36}/></span></div><h3>첫 프레임을 기다리고 있어요</h3><p>PNG를 올리고 작업 방식을 선택하세요<br/>완성된 움직임이 이곳에 나타나요</p></div>}</div><div className="playbar"><button aria-label={playing?'일시정지':'재생'} disabled={!result} onClick={()=>setPlaying(!playing)}>{playing&&result?<Pause size={16}/>:<Play size={16}/>}</button><span className="timeline-label">{result?String(frame+1).padStart(2,'0'):'00'} <span>/ {String(result?.summary.frameCount??0).padStart(2,'0')}</span></span><input aria-label="프레임 위치" type="range" min={0} max={Math.max(0,(result?.summary.frameCount??1)-1)} value={frame} disabled={!result} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/><span className="fps">{result?.summary.fps??fps} FPS</span></div></section>
 <section className="export-panel"><div><p className="eyebrow">READY WHEN YOU ARE</p><h2>원하는 형식으로 가져가세요</h2><p>{result?`${result.summary.frameCount} 프레임 · ${result.summary.frameWidth} × ${result.summary.frameHeight} px / 프레임`:'투명 PNG와 프레임 정보가 함께 준비돼요'}</p></div><div className="exports"><button disabled={!result} onClick={()=>result&&save(result.atlasBase64,'sprite-atlas.png','image/png')}><Grid2X2 size={18}/><span>PNG 아틀라스<small>모든 프레임 한 장에</small></span><ArrowDownToLine size={17}/></button><button disabled={!result} onClick={()=>result&&save(result.atlasJSON,'sprite-atlas.json','application/json',false)}><ScanLine size={18}/><span>JSON 메타데이터<small>좌표 · 타이밍 · 루프</small></span><ArrowDownToLine size={17}/></button><button disabled={!result} onClick={()=>result&&save(result.sequenceZipBase64,'sprite-frames.zip','application/zip')}><Layers size={18}/><span>PNG 프레임 ZIP<small>개별 이미지 모음</small></span><ArrowDownToLine size={17}/></button></div></section><div className="studio-note"><span className="note-dot"/><p>정확하게, 단순하게. AI 생성이나 유료 API 없이 픽셀을 정리해요</p></div></div></div></main><footer><span>dot motion studio</span><span>PNG 중심 · 최대 64 프레임 · 2D 이동</span><a href="/guide">MCP 연결 & 사용법 <ChevronRight size={13}/></a></footer></div>;
}
