/** Standalone bounded PNG integrity audit. Uses only Node built-ins; no network. */
import assert from 'node:assert/strict';
import { deflateSync, inflateSync, constants } from 'node:zlib';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { writeFileSync } from 'node:fs';
const signature=Buffer.from([137,80,78,71,13,10,26,10]);
const crcTable=Uint32Array.from({length:256},(_,i)=>{let c=i;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc(b){let c=0xffffffff;for(const v of b)c=crcTable[(c^v)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function adler(b){let a=1,s=0;for(const x of b){a=(a+x)%65521;s=(s+a)%65521;}return((s<<16)|a)>>>0;}
const u32=n=>{const b=Buffer.alloc(4);b.writeUInt32BE(n);return b;};
function chunk(t,data=[]){data=Buffer.from(data);const name=Buffer.from(t);return Buffer.concat([u32(data.length),name,data,u32(crc(Buffer.concat([name,data])))]);}
export function png(z,{w=1,h=1,depth=8,type=0,split}={}){const hd=Buffer.alloc(13);hd.writeUInt32BE(w);hd.writeUInt32BE(h,4);hd[8]=depth;hd[9]=type;const parts=split?split(z):[z];return Buffer.concat([signature,chunk('IHDR',hd),...parts.map(x=>chunk('IDAT',x)),chunk('IEND')]);}
const rng=seed=>{let s=seed>>>0;return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)>>>24);};
class Bits { constructor(){this.a=[];this.n=0;} bit(v){const p=this.n++;this.a[p>>>3]=(this.a[p>>>3]??0)|((v&1)<<(p&7));} bits(v,n){for(let i=0;i<n;i++)this.bit(v>>>i);} align(fill=0){while(this.n%8)this.bit(fill);} bytes(b){assert.equal(this.n%8,0);for(const v of b)this.bits(v,8);} end(fill=0){this.align(fill);return Buffer.from(this.a);} }
function canonical(lengths){const count=Array(16).fill(0),next=Array(16).fill(0);for(const l of lengths)if(l)count[l]++;for(let b=1,c=0;b<=15;b++){c=(c+count[b-1])*2;next[b]=c;}return lengths.map(l=>l?{n:l,c:next[l]++}:null);}
function symbol(b,table,s){const x=table[s];assert.ok(x,'fixture missing code '+s);for(let j=x.n-1;j>=0;j--)b.bit(x.c>>>j);}
const fl=Array.from({length:288},(_,i)=>i<144?8:i<256?9:i<280?7:8),fd=Array(32).fill(5),ft=canonical(fl),dt=canonical(fd);
const lb=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258];
const le=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0];
const db=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577];
const de=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];
function match(b,len,dist,lt=ft,dd=dt){let i=lb.findLastIndex(v=>v<=len);symbol(b,lt,257+i);b.bits(len-lb[i],le[i]);i=db.findLastIndex(v=>v<=dist);symbol(b,dd,i);b.bits(dist-db[i],de[i]);}
function stored(b,raw,final=false,padding=0,bad=false){b.bits(final?1:0,1);b.bits(0,2);b.align(padding);b.bits(raw.length,16);b.bits((raw.length^0xffff)^(bad?1:0),16);b.bytes(raw);}
function fixed(b,raw,final=true,padding=0){b.bits(final?1:0,1);b.bits(1,2);for(const v of raw)symbol(b,ft,v);symbol(b,ft,256);if(final)b.align(padding);}
const order=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];
function dynHeader(b,ll,dd,{final=true,cl=Array.from({length:19},(_,i)=>i<16?4:0),lengths}={}){b.bits(final?1:0,1);b.bits(2,2);b.bits(ll.length-257,5);b.bits(dd.length-1,5);b.bits(15,4);for(const i of order)b.bits(cl[i],3);const ct=canonical(cl);if(lengths)lengths(b,ct);else for(const l of [...ll,...dd])symbol(b,ct,l);return[canonical(ll),canonical(dd)];}
function wrap(raw,body,cinfo=7,suffix=[]){const cmf=cinfo*16+8;const flg=(31-(cmf*256%31))%31;return Buffer.concat([Buffer.from([cmf,flg]),body,u32(adler(raw)),Buffer.from(suffix)]);}
function rawPixel(raw,shape){const {w,h,depth=8,type=0}=shape;assert.equal(type,0);assert.equal(depth,8);assert.equal(raw.length,(w+1)*h);const out=Buffer.alloc(w*h*4);let p=0;for(let y=0;y<h;y++){assert.equal(raw[y*(w+1)],0);for(let x=0;x<w;x++){const v=raw[y*(w+1)+1+x];out.set([v,v,v,255],p);p+=4;}}return out;}
export function makeCases(){const cases=[];const add=(name,z,raw,opts={})=>{const shape=opts.shape??{w:raw.length-1,h:1};cases.push({name,z,raw,shape,valid:opts.valid??true,oracle:opts.oracle??true,group:opts.group??'crafted',...opts});};
// Independent library-generated valid corpus: 224 streams across patterns and strategies.
for(let k=0;k<224;k++){const w=1+k%31,h=1+Math.floor(k/31)%7,raw=Buffer.alloc((w+1)*h),r=rng(0x504e4700+k);for(let y=0;y<h;y++)for(let x=1;x<=w;x++)raw[y*(w+1)+x]=k%4===0?0:k%4===1?x%3:k%4===2?r():y%2?255:17;const strategies=[constants.Z_DEFAULT_STRATEGY,constants.Z_FIXED,constants.Z_HUFFMAN_ONLY,constants.Z_RLE];const z=deflateSync(raw,{level:k%10,strategy:strategies[Math.floor(k/10)%4],windowBits:9+k%7});add('generated-'+k,z,raw,{shape:{w,h},group:'generated'});}
const zero=Buffer.alloc(5);for(const fill of [0,1]){const b=new Bits();stored(b,zero,true,fill);add('stored-padding-'+fill,wrap(zero,b.end()),zero);const f=new Bits();fixed(f,zero,true,fill);add('fixed-padding-'+fill,wrap(zero,f.end()),zero);}
for(const cinfo of [0,1,2,3,4,5,6,7]){const b=new Bits();fixed(b,zero);add('CINFO-'+cinfo,wrap(zero,b.end(),cinfo),zero);}
for(const dist of [1,2,3,4,5,8,16,32,64,128,256,257,512,1024,4096,32768]){const n=dist+258,total=n<=4097?n:Math.ceil(n/1024)*1024;const raw=Buffer.alloc(total),b=new Bits();b.bits(1,1);b.bits(1,2);for(let j=0;j<dist;j++)symbol(b,ft,0);match(b,258,dist);for(let j=n;j<total;j++)symbol(b,ft,0);symbol(b,ft,256);const shape=total<=4097?{w:total-1,h:1}:{w:1023,h:total/1024};add('distance-'+dist,wrap(raw,b.end()),raw,{shape});if(dist===257)add('distance-exceeds-declared-window',wrap(raw,b.end(),0),raw,{valid:false,oracle:false});}
// Dynamic: literals with zero distance alphabet; single distance tree; EOB-only final block.
{const ll=Array(257).fill(0);ll[0]=ll[256]=1;for(const dd of [[0],[1],Array(30).fill(0),Array(31).fill(0),Array(32).fill(0)]){const b=new Bits();const [lt]=dynHeader(b,ll,dd);for(const v of zero)symbol(b,lt,v);symbol(b,lt,256);add('dynamic-literals-distance-'+dd.length+'-'+dd[0],wrap(zero,b.end()),zero,{advisory:dd.length>30});}}
{const ll=Array(258).fill(0);ll[0]=1;ll[256]=ll[257]=2;const b=new Bits(),[lt,dd]=dynHeader(b,ll,[1]);symbol(b,lt,0);match(b,3,1,lt,dd);symbol(b,lt,0);symbol(b,lt,256);add('dynamic-single-distance-overlap',wrap(zero,b.end()),zero);}
for(const count of [31,32]){const ll=Array(258).fill(0);ll[0]=1;ll[256]=ll[257]=2;const distance=Array(count).fill(0);distance[0]=distance[1]=1;const b=new Bits(),[lt,dd]=dynHeader(b,ll,distance);symbol(b,lt,0);match(b,3,1,lt,dd);symbol(b,lt,0);symbol(b,lt,256);add('dynamic-active-distance-'+count+'-reserved-unused',wrap(zero,b.end()),zero,{advisory:true});}
{const ll=Array(257).fill(0);ll[256]=1;const b=new Bits();stored(b,zero,false,1);const[lt]=dynHeader(b,ll,[0]);symbol(b,lt,256);add('dynamic-eob-only-after-stored',wrap(zero,b.end(1)),zero);}
for(const invalid of [false,true]){const b=new Bits();fixed(b,Buffer.from([0,0]),false);stored(b,Buffer.from([0,0,0]),true,1,invalid);add('fixed-then-stored-'+invalid,wrap(zero,b.end()),zero,{valid:!invalid});}
for(const where of [0,1,2]){const b=new Bits();stored(b,Buffer.from([0]),false,0,where===0);stored(b,Buffer.from([0]),false,0,where===1);stored(b,Buffer.from([0,0,0]),true,0,where===2);add('stored-bad-complement-block-'+where,wrap(zero,b.end()),zero,{valid:false});}
for(const reserved of [286,287]){const b=new Bits();b.bits(3,3);symbol(b,ft,reserved);symbol(b,ft,256);add('reserved-length-'+reserved,wrap(zero,b.end()),zero,{valid:false});}
for(const reserved of [30,31]){const b=new Bits();b.bits(3,3);symbol(b,ft,0);symbol(b,ft,257);symbol(b,dt,reserved);symbol(b,ft,256);add('reserved-distance-'+reserved,wrap(zero,b.end()),zero,{valid:false});}
{const b=new Bits();b.bits(3,3);match(b,3,1);symbol(b,ft,256);add('distance-before-history',wrap(zero,b.end()),zero,{valid:false});}
for(const type of ['over-lit','incomplete-lit','no-eob','over-dist','incomplete-dist']){const ll=Array(257).fill(0);ll[0]=ll[256]=1;let dd=[1];if(type==='over-lit')ll[1]=1;if(type==='incomplete-lit')ll[0]=ll[256]=2;if(type==='no-eob')ll[256]=0;if(type==='over-dist')dd=[1,1,1];if(type==='incomplete-dist')dd=[2,2];const b=new Bits();const[lt]=dynHeader(b,ll,dd);for(let j=0;j<5;j++)symbol(b,lt,0);if(ll[256])symbol(b,lt,256);add('dynamic-'+type,wrap(zero,b.end()),zero,{valid:false});}
for(const type of ['over-cl','incomplete-cl','repeat-16-first','repeat-overflow','hlit-287','hlit-288']){const b=new Bits();b.bits(5,3);b.bits(type==='hlit-287'?30:type==='hlit-288'?31:0,5);b.bits(0,5);b.bits(0,4);const lengths=type==='over-cl'?[1,1,1,1]:type==='incomplete-cl'?[2,0,0,0]:[1,0,1,0];for(const v of lengths)b.bits(v,3);if(type==='repeat-16-first'){b.bit(0);b.bits(0,2);}if(type==='repeat-overflow'){b.bit(1);b.bits(127,7);b.bit(1);b.bits(127,7);}add('dynamic-'+type,wrap(zero,b.end()),zero,{valid:false});}
add('reserved-block-type',wrap(zero,Buffer.from([7])),zero,{valid:false});
const bases=cases.filter(c=>['stored-padding-0','fixed-padding-0','dynamic-literals-distance-1-0','fixed-then-stored-false'].includes(c.name));
for(const c of bases){for(const suffix of [Buffer.from([0]),Buffer.alloc(8),Buffer.from([1,2,0xff,0xff]),Buffer.from([0x78,0x9c]),deflateSync(zero),c.z.subarray(-4)])add(c.name+'-suffix-'+suffix.toString('hex'),Buffer.concat([c.z,suffix]),c.raw,{group:'suffix'});const corrupt=Buffer.from(c.z);corrupt[corrupt.length-1]^=1;add(c.name+'-bad-adler-good-tail',Buffer.concat([corrupt,c.z.subarray(-4)]),c.raw,{valid:false,group:'suffix'});for(let n=0;n<c.z.length;n++)add(c.name+'-truncate-'+n,c.z.subarray(0,n),c.raw,{valid:false,group:'truncation'});for(let byte=0;byte<c.z.length;byte++)for(let bit=0;bit<8;bit++){const z=Buffer.from(c.z);z[byte]^=1<<bit;let raw,valid=false;try{raw=inflateSync(z,{maxOutputLength:4096});valid=raw.length===zero.length&&raw[0]===0;}catch{}add(c.name+'-flip-'+byte+'-'+bit,z,raw??c.raw,{valid,shape:{w:4,h:1},group:'mutation'});}}
for(const b of [0,1,2,3,4,5,6]){const z=Buffer.from(deflateSync(zero));if(b===0)z[0]=0x88;else if(b===1)z[0]=0x79;else if(b===2)z[1]^=1;else if(b===3){z[1]=0x20;z[1]+=((31-(z[0]*256+z[1])%31)%31);}else z[z.length-(b-3)]^=1;add('header-trailer-invalid-'+b,z,zero,{valid:false});}
return cases;}
export async function runAudit(enginePath,outputPath){const engine=await import(pathToFileURL(resolve(enginePath)));const allCases=makeCases(),advisories=allCases.filter(c=>c.advisory),cases=allCases.filter(c=>!c.advisory),results=[],stats={};let oracleFailures=0;for(const c of cases){let oracle='skipped';if(c.oracle){try{const raw=inflateSync(c.z,{maxOutputLength:10_000_000});const valid=raw.length===(c.shape.w+1)*c.shape.h&&Array.from({length:c.shape.h},(_,y)=>raw[y*(c.shape.w+1)]).every(v=>v===0);assert.equal(valid,c.valid);if(c.valid)assert.deepEqual(raw,c.raw);oracle='pass';}catch(e){if(!c.valid&&!e.code?.startsWith('ERR_ASSERTION'))oracle='pass';else {oracle='FAIL '+e.message;oracleFailures++;}}}
const start=performance.now();let status='PASS',error;try{const original=Buffer.from(c.z),out=engine.decodePNG(png(c.z,c.shape));assert.ok(c.valid,'accepted invalid stream');assert.deepEqual(Buffer.from(out.data),rawPixel(c.raw,c.shape));assert.deepEqual(c.z,original,'mutated input');}catch(e){if(c.valid||e.name!=='MotionError'||!['INVALID_PNG','UNSUPPORTED_PNG'].includes(e.code)){status='FAIL';error=e.message;}}const ms=performance.now()-start;stats[c.group]??={total:0,pass:0};stats[c.group].total++;stats[c.group].pass+=status==='PASS';results.push({name:c.name,valid:c.valid,status,oracle,ms,error});}
const advisoryResults=advisories.map(c=>{const result={name:c.name,zlibHex:c.z.toString('hex'),pngBase64:png(c.z,c.shape).toString('base64'),rawHex:c.raw.toString('hex')};try{engine.decodePNG(png(c.z,c.shape));result.candidate='ACCEPT';}catch(e){result.candidate='REJECT '+e.message;}try{inflateSync(c.z);result.node='ACCEPT';}catch(e){result.node='REJECT '+e.message;}return result;});const summary={advisoryResults,enginePath,node:process.version,cases:cases.length,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,oracleFailures,stats,slowest:[...results].sort((a,b)=>b.ms-a.ms).slice(0,5)};if(outputPath)writeFileSync(outputPath,JSON.stringify({summary,results},null,2));console.log(JSON.stringify(summary,null,2));for(const r of results.filter(r=>r.status==='FAIL'||r.oracle.startsWith('FAIL')))console.log(r);return{summary,results};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const r=await runAudit(process.argv[2],process.argv[3]);process.exitCode=r.summary.failed||r.summary.oracleFailures?1:0;}
